"""/***************************************************************************
 MoveLayersToGPKGDialog
                                 A QGIS plugin
 This plugin renames selected layers (if they are nested in groups)
 and moves them to a new GeoPackage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Florian Ludwig
        email                : lasinludwig@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from pathlib import Path

from qgis.core import QgsLayerTreeModel, QgsProject
from qgis.gui import QgsLayerTreeView
from qgis.PyQt import QtWidgets, uic

# This loads your .ui file so that PyQt can populate
# your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    str(Path(__file__).parent / "move_layers_to_gpkg_dialog_base.ui")
)


class MoveLayersToGPKGDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, plugin, parent=None) -> None:
        """Initialize the dialog window."""
        super().__init__(parent)
        self.plugin = plugin
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Connect the button to the plugin's method.
        self.rename_Button_FL.clicked.connect(self.plugin.rename_selected_layers)

        # --- Replace QTreeView placeholder with QgsLayerTreeView ---
        # The .ui file uses a standard QTreeView. To get QGIS-specific
        # functionality like node renaming flags, we must use a QgsLayerTreeView.
        # This code replaces the placeholder widget with the correct one at runtime.
        original_tree_view = self.Layer_Tree_FL
        new_tree_view = QgsLayerTreeView(self)
        # It's good practice to keep the same object name.
        new_tree_view.setObjectName(original_tree_view.objectName())

        # Replace the widget in its parent's layout.
        original_tree_view.parent().layout().replaceWidget(
            original_tree_view, new_tree_view
        )
        original_tree_view.deleteLater()
        self.Layer_Tree_FL = new_tree_view
        # --- End of replacement ---

        # Set up the layer tree view model and flags.
        self.layer_tree_model = QgsLayerTreeModel(QgsProject.instance().layerTreeRoot())
        self.Layer_Tree_FL.setModel(self.layer_tree_model)
        self.layer_tree_model.setFlag(QgsLayerTreeModel.AllowNodeRename)

        # Allow layers and groups to be renamed directly in the tree view
        # by slow-clicking or pressing F2.
        self.layer_tree_model.setFlag(QgsLayerTreeModel.AllowNodeRename)
