"""*******************************************************************
***************************************************************************
 UTECLayerTools


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder
                              -------------------
        begin                : 2025-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Florian Ludwig
        email                : immerse-vowel-dole@duck.com
 ***************************************************************************

***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************
"""

import configparser
import contextlib
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING

from qgis.core import Qgis, QgsLayerTree, QgsMapLayer, QgsProject
from qgis.gui import QgisInterface
from qgis.PyQt.QtCore import (
    QCoreApplication,
    QObject,
    QSettings,
    QTimer,
    QTranslator,
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMenu,
    QToolButton,
)

from . import resources
from .modules import general as ge
from .modules import logs_and_errors as lae
from .modules.general import get_current_project
from .modules.geopackage import move_layers_to_gpkg
from .modules.layer_location import add_location_indicator
from .modules.rename import rename_layers, undo_rename_layers

if TYPE_CHECKING:
    from qgis.gui import QgsLayerTreeView, QgsMessageBar


class UTECLayerTools(QObject):  # pylint: disable=too-many-instance-attributes
    """QGIS Plugin for actions on layers."""

    def __init__(self, iface: QgisInterface) -> None:
        """Initialize the plugin.

        Args:
            iface: An interface instance that allows interaction with QGIS.
        """
        super().__init__()
        self.project: QgsProject = get_current_project()
        self.iface: QgisInterface = iface
        self.msg_bar: QgsMessageBar | None = iface.messageBar()
        ge.iface = iface
        self.plugin_dir: Path = Path(__file__).parent
        self.actions: list = []
        self.plugin_menu: QMenu | None = None
        self.icon_path = ":/compiled_resources_LayerTools/icon.svg"
        self.translator: QTranslator | None = None
        self.location_indicators: dict = {}

        # Read metadata to get the plugin name for UI elements
        self.plugin_name: str = "UTEC Layer Tools (dev)"
        metadata_path: Path = self.plugin_dir / "metadata.txt"
        if metadata_path.exists():
            config = configparser.ConfigParser()
            config.read(metadata_path)
            try:
                self.plugin_name = config.get("general", "name")
            except (configparser.NoSectionError, configparser.NoOptionError):
                lae.log_debug("Could not read name from metadata.txt", Qgis.Warning)

        self.menu: str = self.plugin_name

        # initialize translation
        locale = QSettings().value("locale/userLocale", "en")[:2]
        translator_path: Path = self.plugin_dir / "i18n" / f"{locale}.qm"

        if not translator_path.exists():
            lae.log_debug(f"Translator not found in: {translator_path}", Qgis.Warning)
        else:
            self.translator = QTranslator()
            if self.translator is not None and self.translator.load(
                str(translator_path)
            ):
                QCoreApplication.installTranslator(self.translator)
            else:
                lae.log_debug("Translator could not be installed.", Qgis.Warning)

    def add_action(  # noqa: PLR0913 # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        icon_path: str,
        text: str,
        callback: Callable,
        enabled_flag: bool = True,  # noqa: FBT001, FBT002
        add_to_menu: bool = True,  # noqa: FBT001, FBT002
        add_to_toolbar: bool = True,  # noqa: FBT001, FBT002
        status_tip: str | None = None,
        whats_this: str | None = None,
        parent=None,  # noqa: ANN001
    ) -> QAction:  # type: ignore[]
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file path
            (e.g. '/path/to/icon.png').
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should (and should
            not) be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should (and
            should not) be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Text that should be shown in a status bar when
            the mouse pointer hovers over the action. For menus and toolbars,
            this is often longer explanation text.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Text document that goes into the 'whatsThis' help
            section.
        :type whats_this: str

        :returns: The action that was created. As a widget, this can be added
            to menus and toolbars.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self) -> None:  # noqa: N802
        """Create the menu entries and toolbar icons for the plugin."""

        # Initialize the resources (icons, etc.)
        resources.qInitResources()

        # Create a menu for the plugin in the "Plugins" menu
        self.plugin_menu = QMenu(self.menu, self.iface.pluginMenu())
        if self.plugin_menu is None:
            # fmt: off
            error_msg: str = QCoreApplication.translate("RuntimeError", "Failed to create the plugin menu.")
            # fmt: on
            lae.raise_runtime_error(error_msg)

        self.plugin_menu.setIcon(QIcon(self.icon_path))

        # Add an action for renaming layers
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Rename Layers by Group")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Rename selected layers to their parent group names")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Renames selected layers to match their parent group's name.")
        # fmt: on
        rename_action = self.add_action(
            icon_path=":/compiled_resources_LayerTools/icons/main_rename.svg",
            text=menu_main,
            callback=self.rename_selected_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Will be added to our custom menu
            add_to_toolbar=False,  # Avoid creating a separate toolbar button
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(rename_action)

        # Add an action for undoing the last rename
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Undo Last Rename")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Reverts the last layer renaming operation")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Undoes the most recent layer renaming operation performed by this plugin.")
        # fmt: on
        undo_rename_action = self.add_action(
            icon_path=":/compiled_resources_LayerTools/icons/main_undo.svg",
            text=menu_main,
            callback=self.undo_last_rename,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(undo_rename_action)

        # Add an action for moving layers
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Move Layers to GeoPackage")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Move selected layers to the project's GeoPackage")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Copies selected layers to the project's GeoPackage (a GeoPackage in the project folder with the same name as the project file) and adds them back from the GeoPackage to the layer tree of the project.")
        # fmt: on
        move_action = self.add_action(
            icon_path=":/compiled_resources_LayerTools/icons/main_move.svg",
            text=menu_main,
            callback=self.move_selected_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(move_action)

        # Add an action for renaming and moving layers
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Rename and Move Layers to GeoPackage")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Rename and move selected layers to the project's GeoPackage")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Renames the selected layers to their parent group names, then copies them to the project's GeoPackage (a GeoPackage in the project folder with the same name as the project file) and adds them back from the GeoPackage to the layer tree of the project.")
        # fmt: on
        rename_move_action = self.add_action(
            icon_path=":/compiled_resources_LayerTools/icons/main_rename_move.svg",
            text=menu_main,
            callback=self.rename_and_move_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(rename_move_action)

        # Add the fly-out menu to the main "Plugins" menu
        if menu := self.iface.pluginMenu():
            menu.addMenu(self.plugin_menu)
        toolbar_button = QToolButton()
        toolbar_button.setIcon(QIcon(self.icon_path))
        toolbar_button.setToolTip(self.plugin_name)
        toolbar_button.setMenu(self.plugin_menu)
        toolbar_button.setPopupMode(QToolButton.InstantPopup)
        toolbar_action = self.iface.addToolBarWidget(toolbar_button)
        self.actions.append(toolbar_action)

        # Create the location indicators for the location of the layer source data
        self._update_all_location_indicators()
        self.project.readProject.connect(self._update_all_location_indicators)
        self.project.layerWasAdded.connect(self._on_layer_added)
        self.project.layerWillBeRemoved.connect(self._on_layer_removed)

    def unload(self) -> None:
        """Plugin unload method.

        Called when the plugin is unloaded according to the plugin QGIS metadata.
        """
        # Unregister the layer tree view indicator
        view: QgsLayerTreeView | None = self.iface.layerTreeView()
        root: QgsLayerTree | None = self.project.layerTreeRoot()
        if view and root and self.location_indicators:
            self._clear_all_location_indicators()

        if self.project:
            with contextlib.suppress(Exception):
                self.project.readProject.disconnect()
            with contextlib.suppress(Exception):
                self.project.layerWasAdded.disconnect()
            with contextlib.suppress(Exception):
                self.project.layerWillBeRemoved.disconnect()

        # Remove toolbar icons for all actions
        for action in self.actions:
            self.iface.removeToolBarIcon(action)

        # Remove the plugin menu from the "Plugins" menu.
        if self.plugin_menu and (menu := self.iface.pluginMenu()):
            menu.removeAction(self.plugin_menu.menuAction())

        # Remove the translator
        if self.translator:
            QCoreApplication.removeTranslator(self.translator)

        self.actions.clear()
        self.plugin_menu = None

        # Unload resources to allow for reloading them
        resources.qCleanupResources()

    def _clear_all_location_indicators(self) -> None:
        """Remove all location indicators from the layer tree view."""
        view: QgsLayerTreeView | None = self.iface.layerTreeView()
        root: QgsLayerTree | None = self.project.layerTreeRoot()
        if not view or not root or not self.location_indicators:
            return

        for layer, indicator in self.location_indicators.items():
            if node := root.findLayer(layer.id()):
                view.removeIndicator(node, indicator)

        self.location_indicators.clear()
        lae.log_debug("Cleared all location indicators.")

    def _update_all_location_indicators(self) -> None:
        """Update location indicators for all layers in the project."""
        self._clear_all_location_indicators()
        if root := self.project.layerTreeRoot():
            for layer_node in root.findLayers():
                if layer_node and (map_layer := layer_node.layer()):
                    self._add_indicator_for_layer(map_layer)

    def _add_indicator_for_layer(self, layer: QgsMapLayer) -> None:
        """Add a location indicator for a single layer."""
        if layer in self.location_indicators:
            lae.log_debug(f"Indicator already exists for layer '{layer.name()}'")
            return

        if indicator := add_location_indicator(self.project, self.iface, layer):
            lae.log_debug(
                f"Location indicator added for layer '{layer.name()}': {indicator.icon()}"
            )
            self.location_indicators[layer] = indicator

    def _on_layer_added(self, layer: QgsMapLayer) -> None:
        """Handle the layerWasAdded signal.

        Args:
            layer: The layer that was added.
        """
        # Use a single shot timer to ensure the layer tree node exists
        # before we try to add the indicator.
        lae.log_debug(f"Layer added: '{layer.name()}', queueing indicator update.")
        QTimer.singleShot(0, lambda: self._add_indicator_for_layer(layer))

    def _on_layer_removed(self, layer_id: str) -> None:
        """Handle the layerWillBeRemoved signal.

        Args:
            layer_id: The ID of the layer that will be removed.
        """
        if layer_to_remove := next(
            (layer for layer in self.location_indicators if layer.id() == layer_id),
            None,
        ):
            del self.location_indicators[layer_to_remove]
            lae.log_debug(f"Indicator removed for layer ID: {layer_id}")

    def rename_selected_layers(self) -> None:
        """Call rename function from 'functions_rename.py'."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (rename_selected_layers)", icon="✨✨✨"
        )
        try:
            rename_layers()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return

    def move_selected_layers(self) -> None:
        """Call move function from 'functions_geopackage.py'."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (move_selected_layers)", icon="✨✨✨"
        )
        try:
            move_layers_to_gpkg()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return

    def undo_last_rename(self) -> None:
        """Call undo function from 'modules/rename.py'."""
        lae.log_debug("... STARTING PLUGIN RUN ... (undo_last_rename)", icon="✨✨✨")
        try:
            undo_rename_layers()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return

    def rename_and_move_layers(self) -> None:
        """Combine the rename and move functions."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (rename_and_move_layers)", icon="✨✨✨"
        )
        try:
            rename_layers()
            move_layers_to_gpkg()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return
