"""*******************************************************************
***************************************************************************
 UTECLayerTools


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder
                              -------------------
        begin                : 2025-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Florian Ludwig
        email                : immerse-vowel-dole@duck.com
 ***************************************************************************

***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************
"""

import configparser
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING

from qgis.core import Qgis, QgsProject
from qgis.gui import QgisInterface
from qgis.PyQt.QtCore import (
    QCoreApplication,
    QSettings,
    QTimer,
    QTranslator,
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMenu,
    QToolButton,
)

from . import resources
from .modules import general as ge
from .modules import logs_and_errors as lae
from .modules.general import clear_layer_location_cache
from .modules.geopackage import move_layers_to_gpkg
from .modules.rename import rename_layers, undo_rename_layers
from .modules.source_indicator import LayerLocationDelegate

if TYPE_CHECKING:
    from qgis.gui import QgsMessageBar


class UTECLayerTools:  # pylint: disable=too-many-instance-attributes
    """QGIS Plugin for renaming and moving layers to a GeoPackage."""

    def __init__(self, iface: QgisInterface) -> None:
        """Initialize the plugin.

        :param iface: An interface instance that allows interaction with QGIS.
        """

        self.iface: QgisInterface = iface
        self.msg_bar: QgsMessageBar | None = iface.messageBar()
        ge.iface = iface
        self.plugin_dir: Path = Path(__file__).parent
        self.actions: list = []
        self.plugin_menu: QMenu | None = None
        self.icon_path = ":/compiled_resources/icon.png"
        self.translator: QTranslator | None = None
        self.location_delegate: LayerLocationDelegate | None = None
        self._indicator_global: bool = False
        lae.log_debug("Plugin init: created UTECLayerTools instance")

        # Read metadata to get the plugin name for UI elements
        self.plugin_name: str = "UTEC Layer Tools (dev)"
        metadata_path: Path = self.plugin_dir / "metadata.txt"
        if metadata_path.exists():
            config = configparser.ConfigParser()
            config.read(metadata_path)
            try:
                self.plugin_name = config.get("general", "name")
            except (configparser.NoSectionError, configparser.NoOptionError):
                lae.log_debug("Could not read name from metadata.txt", Qgis.Warning)

        self.menu: str = self.plugin_name

        # initialize translation
        locale = QSettings().value("locale/userLocale", "en")[:2]
        translator_path: Path = self.plugin_dir / "i18n" / f"{locale}.qm"

        if not translator_path.exists():
            lae.log_debug(f"Translator not found in: {translator_path}", Qgis.Warning)
        else:
            self.translator = QTranslator()
            if self.translator is not None and self.translator.load(
                str(translator_path)
            ):
                QCoreApplication.installTranslator(self.translator)
            else:
                lae.log_debug("Translator could not be installed.", Qgis.Warning)

    def add_action(  # noqa: PLR0913 # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        icon_path: str,
        text: str,
        callback: Callable,
        enabled_flag: bool = True,  # noqa: FBT001, FBT002
        add_to_menu: bool = True,  # noqa: FBT001, FBT002
        add_to_toolbar: bool = True,  # noqa: FBT001, FBT002
        status_tip: str | None = None,
        whats_this: str | None = None,
        parent=None,  # noqa: ANN001
    ) -> QAction:  # type: ignore[]
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file path
            (e.g. '/path/to/icon.png').
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should (and should
            not) be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should (and
            should not) be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Text that should be shown in a status bar when
            the mouse pointer hovers over the action. For menus and toolbars,
            this is often longer explanation text.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Text document that goes into the 'whatsThis' help
            section.
        :type whats_this: str

        :returns: The action that was created. As a widget, this can be added
            to menus and toolbars.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self) -> None:  # noqa: N802
        """Create the menu entries and toolbar icons for the plugin."""

        # Initialize the resources (icons, etc.)
        resources.qInitResources()

        # Create a menu for the plugin in the "Plugins" menu
        self.plugin_menu = QMenu(self.menu, self.iface.pluginMenu())
        if self.plugin_menu is None:
            # fmt: off
            error_msg: str = QCoreApplication.translate("RuntimeError", "Failed to create the plugin menu.")
            # fmt: on
            lae.raise_runtime_error(error_msg)

        self.plugin_menu.setIcon(QIcon(self.icon_path))

        # Create the source indicator for the location of the layer source data
        self.setup_source_indicator()

        # Add an action for updating layers source location indicators
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Reload locaction indicators")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Reloads the location indicators for all layers in the project.")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "The location indicators show the location for the source data for each layer.")
        # fmt: on
        refresh_action = self.add_action(
            self.icon_path,
            text=menu_main,
            callback=self.refresh_indicators,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Will be added to our custom menu
            add_to_toolbar=False,  # Avoid creating a separate toolbar button
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(refresh_action)

        # Add an action for renaming layers
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Rename Layers by Group")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Rename selected layers to their parent group names")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Renames selected layers to match their parent group's name.")
        # fmt: on
        rename_action = self.add_action(
            self.icon_path,
            text=menu_main,
            callback=self.rename_selected_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Will be added to our custom menu
            add_to_toolbar=False,  # Avoid creating a separate toolbar button
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(rename_action)

        # Add an action for undoing the last rename
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Undo Last Rename")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Reverts the last layer renaming operation")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Undoes the most recent layer renaming operation performed by this plugin.")
        # fmt: on
        undo_rename_action = self.add_action(
            self.icon_path,
            text=menu_main,
            callback=self.undo_last_rename,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(undo_rename_action)

        # Add an action for moving layers
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Move Layers to GeoPackage")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Move selected layers to the project's GeoPackage")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Copies selected layers to the project's GeoPackage (a GeoPackage in the project folder with the same name as the project file) and adds them back from the GeoPackage to the layer tree of the project.")
        # fmt: on
        move_action = self.add_action(
            self.icon_path,
            text=menu_main,
            callback=self.move_selected_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(move_action)

        # Add an action for renaming and moving layers
        # fmt: off
        # ruff: noqa: E501
        menu_main: str = QCoreApplication.translate("Menu_main", "Rename and Move Layers to GeoPackage")
        menu_tip: str = QCoreApplication.translate("Menu_tip", "Rename and move selected layers to the project's GeoPackage")
        menu_whats: str = QCoreApplication.translate("Menu_whats", "Renames the selected layers to their parent group names, then copies them to the project's GeoPackage (a GeoPackage in the project folder with the same name as the project file) and adds them back from the GeoPackage to the layer tree of the project.")
        # fmt: on
        rename_move_action = self.add_action(
            self.icon_path,
            text=menu_main,
            callback=self.rename_and_move_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            status_tip=menu_tip,
            whats_this=menu_whats,
        )
        self.plugin_menu.addAction(rename_move_action)

        # Add the fly-out menu to the main "Plugins" menu
        self.iface.pluginMenu().addMenu(self.plugin_menu)  # type: ignore[]

        # Add a toolbutton to the toolbar to show the flyout menu
        toolbar_button = QToolButton()
        toolbar_button.setMenu(self.plugin_menu)
        toolbar_button.setDefaultAction(rename_action)  # Use an action's icon
        toolbar_button.setPopupMode(QToolButton.InstantPopup)
        toolbar_action = self.iface.addToolBarWidget(toolbar_button)
        self.actions.append(toolbar_action)

    def setup_source_indicator(self) -> None:
        """Initialize and connect the layer source indicator (issue #1 and #7)."""
        view: ge.QgsLayerTreeView | None = self.iface.layerTreeView()
        if view is None:
            lae.log_debug("Indicator setup: no layer tree view", Qgis.Warning)
            return

        # This is the most backward-compatible method. We replace the default
        # delegate with our custom one, which first calls the original
        # delegate's paint method and then paints our icon on top.
        base_delegate = view.itemDelegate()
        self.location_delegate = LayerLocationDelegate(view, base_delegate)
        view.setItemDelegate(self.location_delegate)
        lae.log_debug("Indicator setup: custom delegate has been set")

        project = QgsProject.instance()
        root_node = project.layerTreeRoot()

        def _refresh_view_only() -> None:
            """Force a repaint of the layer tree view."""
            lae.log_debug("Delegate: refresh requested")
            if view and view.viewport():
                view.viewport().update()

        # On changes: clear cache, re-attach (for fallback), and refresh
        def _rebind_and_refresh_all() -> None:
            lae.log_debug("Signal: rebind_all")
            clear_layer_location_cache()
            # Defer refresh to allow QGIS to process changes first
            QTimer.singleShot(0, _refresh_view_only)

        def _on_layer_added(layer) -> None:  # type: ignore[no-redef]
            lae.log_debug(f"Signal: layerWasAdded id={layer.id()} name={layer.name()}")
            clear_layer_location_cache()
            QTimer.singleShot(0, _refresh_view_only)

        def _on_layer_removed(_layer_id: str) -> None:
            lae.log_debug(f"Signal: layerWillBeRemoved id={_layer_id}")
            clear_layer_location_cache()
            QTimer.singleShot(0, _refresh_view_only)

        project.readProject.connect(_rebind_and_refresh_all)
        root_node.customPropertyChanged.connect(_rebind_and_refresh_all)
        project.layerWasAdded.connect(_on_layer_added)
        project.layerWillBeRemoved.connect(_on_layer_removed)

    def unload(self) -> None:
        """Plugin unload method.

        Called when the plugin is unloaded according to the plugin QGIS metadata.
        """
        # Disconnect indicator signals
        project = QgsProject.instance()
        if project:
            root = project.layerTreeRoot()
            try:
                project.readProject.disconnect()
            except Exception:
                pass
            try:
                root.customPropertyChanged.disconnect()
            except Exception:
                pass
            except AttributeError:  # root might be None
                pass

        # Remove toolbar icons for all actions
        for action in self.actions:
            self.iface.removeToolBarIcon(action)

        # Remove the plugin menu from the "Plugins" menu.
        if self.plugin_menu and (menu := self.iface.pluginMenu()):
            menu.removeAction(self.plugin_menu.menuAction())

        # Remove the translator
        if self.translator:
            QCoreApplication.removeTranslator(self.translator)

        self.actions.clear()
        self.plugin_menu = None

        # Unload resources to allow for reloading them
        resources.qCleanupResources()

    def refresh_indicators(self) -> None:
        """Safely refresh indicators if available."""
        try:
            lae.log_debug("Action: manual refresh indicators")
            view = self.iface.layerTreeView()
            if view and view.viewport():
                view.viewport().update()
        except Exception as e:
            lae.log_debug(f"Manual refresh failed: {e}")

    def rename_selected_layers(self) -> None:
        """Call rename function from 'functions_rename.py'."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (rename_selected_layers)", icon="✨✨✨"
        )
        try:
            rename_layers()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return

    def move_selected_layers(self) -> None:
        """Call move function from 'functions_geopackage.py'."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (move_selected_layers)", icon="✨✨✨"
        )
        try:
            move_layers_to_gpkg()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return

    def undo_last_rename(self) -> None:
        """Call undo function from 'modules/rename.py'."""
        lae.log_debug("... STARTING PLUGIN RUN ... (undo_last_rename)", icon="✨✨✨")
        try:
            undo_rename_layers()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return

    def rename_and_move_layers(self) -> None:
        """Combine the rename and move functions."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (rename_and_move_layers)", icon="✨✨✨"
        )
        try:
            rename_layers()
            move_layers_to_gpkg()
        except (lae.CustomUserError, lae.CustomRuntimeError):
            return
